config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :apartments
  
  root "apartments#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
      if user.nil?
        # if no user logged in, use a dummy user, see later
        user = User.new
      end
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :landlord
        # landlord can see all apartment listings
        can :read, Apartment
        #landlord can manage all apartments which they have created
        can :manage, Apartment, user_id: user_id
      else
        #renters can view apartment listings made by any user
        can :read, Apartment
      end
    end
  end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :user
  resourcify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :apartments #add this line
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :assign_role
# after a new user is created assign them the renter role
  def assign_role
    add_role(:renter)
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show] #add this line
  load_and_authorize_resource   # add this line
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
    @ability = Ability.new(current_user)
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:street1, :street2, :city, :postal_code, :state, :country, :name, :phone_number, :hours, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.erb
<%= form_for(apartment) do |f| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street1 %>
    <%= f.text_field :street1 %>
  </div>

  <div class="field">
    <%= f.label :street2 %>
    <%= f.text_field :street2 %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :postal_code %>
    <%= f.number_field :postal_code %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.number_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :hours %>
    <%= f.text_field :hours %>
  </div>
  <div class="field">

    <%= f.hidden_field :user_id, :value => current_user.id %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Street1</th>
      <th>Street2</th>
      <th>City</th>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th>Name</th>
      <th>Phone number</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.street1 %></td>
        <td><%= apartment.street2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.postal_code %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone_number %></td>
        <td><%= apartment.hours %></td>
        <td><%= link_to 'Show', apartment %></td>
        <!--does the user have autorization?  -->
          <% if can? :manage, :all %>
          <!--show if authorized  -->
            <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
            <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!--does the user have autorization?  -->
<% if can? :manage, :all %>
<!--show if authorized  -->
  <%= link_to 'New Apartment', new_apartment_path %>
<% end %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street1:</strong>
  <%= @apartment.street1 %>
</p>

<p>
  <strong>Street2:</strong>
  <%= @apartment.street2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @apartment.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @apartment.phone_number %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @apartment.hours %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AptApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- navigation -->
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Apartments For You", apartments_path, class: 'navbar-brand' %>
      </div>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <%= link_to 'Log in', new_user_session_path, method: :get %></li>
              <% if current_user %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav> <!-- END NAVBAR -->
  <p>
  <%= if !current_user.nil?
        current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
      end
  %>
</p>
    <%= yield %>
  </body>
</html>